version: '3'

services:

    hshs-domxss-scanner:
        image: siwecos/hshs-domxss-scanner:latest
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_DB=2
            - REDIS_CACHE_DB=3

    ini-s-scanner:
        image: siwecos/ini-s-scanner:latest
        volumes:
            - blacklists:/storage

    infoleak-scanner:
        image: siwecos/infoleak-scanner:latest
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_DB=4
            - REDIS_CACHE_DB=5
            - REDIS_CLIENT=phpredis

    port-scanner:
        image: siwecos/ws-port-scanner:latest

    tls-scanner:
        image: siwecos/ws-tls-scanner:latest

    version-scanner:
        image: siwecos/version-scanner:latest
        depends_on:
            - redis
        volumes:
            - signatures:/scanner/storage/signatures
        environment:
            - REDIS_HOST=redis
            - REDIS_DB=6
            - REDIS_CACHE_DB=7
            - REDIS_CLIENT=phpredis

    siwecos-core-api:
        image: siwecos/siwecos-core-api:latest
        ports:
            - 127.0.0.1:80:80
        depends_on:
            - mariadb
            - redis
        environment:
            - APP_URL=http://siwecos-core-api
            - INI_S_SCANNER_URL=http://ini-s-scanner:8080/api/v1/check
            - DOMXSS_SCANNER_URL=http://hshs-domxss-scanner/api/v1/domxss
            - INFOLEAK_SCANNER_URL=http://infoleak-scanner/api/v2/start
            - HEADER_SCANNER_URL=http://hshs-domxss-scanner/api/v1/header
            - PORT_SCANNER_URL=http://port-scanner:8080/start
            - HTTPS_SCANNER_URL=http://tls-scanner:8080/https
            # - MAIL_SCANNER_URL=
            - VERSION_SCANNER_URL=http://version-scanner/api/v1/version
            # - USER_AGENT=
            - REDIS_HOST=redis
            - REDIS_DB=0
            - REDIS_CACHE_DB=1
            - DB_CONNECTION=mysql
            - DB_HOST=mariadb
            - DB_USERNAME=siwecos
            - DB_PASSWORD=siwecos
            - DB_DATABASE=coreApi
            - REDIS_CLIENT=phpredis
            - LOG_CHANNEL=stderr

    mariadb:
        image: mariadb
        volumes:
            - db:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=siwecosRoot
            - MYSQL_USER=siwecos
            - MYSQL_PASSWORD=siwecos
            - MYSQL_DATABASE=coreApi

    redis:
        image: redis

    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock

volumes:
    caddy_certs:
    db:
    signatures:
    blacklists:
