version: '3'

services:

    # blacklist-scanner:
    #     image: siwecos/ini-s-scanner:develop
    #     ports:
    #         - 8090:8080

    hshs-domxss-scanner:
        image: siwecos/hshs-domxss-scanner:develop
        ports:
            - 8091:80

    infoleak-scanner:
        image: siwecos/infoleak-scanner:develop
        ports:
            - 8093:80

    port-scanner:
        image: siwecos/ws-port-scanner:develop
        ports:
            - 8094:8080

    tls-scanner:
        image: siwecos/ws-tls-scanner:develop
        ports:
            - 8095:8080

    version-scanner:
        image: siwecos/version-scanner:develop
        ports:
            - 8096:80
        volumes:
            - signatures:/scanner/storage/signatures

    callback:
        image: siwecos/callback-server:latest
        ports:
            - 3000:3000
        volumes:
            - ./data:/data

    siwecos-core-api:
        image: siwecos/siwecos-core-api:develop
        ports:
            - 8000:80
        environment:
            - APP_URL=http://siwecos-core-api
            # - BLACKLIST_SCANNER_URL=http://blacklist-scanner:8080/api/v1/check
            - DOMXSS_SCANNER_URL=http://hshs-domxss-scanner/api/v1/domxss
            - HEADER_SCANNER_URL=http://hshs-domxss-scanner/api/v1/header
            - INFOLEAK_SCANNER_URL=http://infoleak-scanner
            - PORT_SCANNER_URL=http://port-scanner:8080/start
            - HTTPS_SCANNER_URL=http://tls-scanner:8080/https
            - POP3_SCANNER_URL=http://tls-scanner:8080/pop3
            - POP3S_SCANNER_URL=http://tls-scanner:8080/pop3s
            - IMAP_SCANNER_URL=http://tls-scanner:8080/imap
            - IMAPS_SCANNER_URL=http://tls-scanner:8080/imaps
            - SMTP_SCANNER_URL=http://tls-scanner:8080/smtp
            - SMTPS_SCANNER_URL=http://tls-scanner:8080/smtps
            - VERSION_SCANNER_URL=http://version-scanner/api/v1/version
            - USER_AGENT=
            - APP_DEBUG=true
            - LOG_CHANNEL=stderr

volumes:
    signatures:
