version: '2'

services:

    header-domxss-scanner:
        image: siwecos/hshs-domxss-scanner
        ports:
            - 8090:2015

    infoleak-scanner:
        image: siwecos/infoleak-scanner
        ports:
            - 8091:80

    ws-tls-scanner:
        image: siwecos/ws-tls-scanner
        ports:
            - 8092:8080

