version: '3'

services:

    hshs-domxss-scanner:
        image: siwecos/hshs-domxss-scanner:latest
        depends_on:
            - redis
        environment:
            - REDIS_HOST=redis
            - REDIS_DB=2
            - REDIS_CACHE_DB=3

    infoleak-scanner:
        image: siwecos/infoleak-scanner:latest

    ws-port-scanner:
        image: siwecos/ws-port-scanner:latest

    ws-tls-scanner:
        image: siwecos/ws-tls-scanner:latest

    version-scanner:
        image: siwecos/version-scanner:latest
        depends_on:
            - redis
        volumes:
            - signatures_production:/scanner/storage/signatures
        environment:
            - REDIS_HOST=redis
            - REDIS_DB=4
            - REDIS_CACHE_DB=5

    siwecos-core-api:
        image: siwecos/siwecos-core-api:latest
        ports:
            - 8000:80
        depends_on:
            - mariadb
            - redis
        environment:
            - APP_URL=http://siwecos-core-api
            # - BLACKLIST_SCANNER_URL=http://blacklist-scanner/api/v1/check
            - DOMXSS_SCANNER_URL=http://hshs-domxss-scanner:2015/api/v1/domxss
            - INFOLEAK_SCANNER_URL=http://infoleak-scanner:80
            - HEADER_SCANNER_URL=http://hshs-domxss-scanner:2015/api/v1/header
            # - MAIL_SCANNER_URL=
            - PORT_SCANNER_URL=http://ws-port-scanner:8080/start
            - TLS_SCANNER_URL=http://ws-tls-scanner:8080/start
            - VERSION_SCANNER_URL=http://version-scanner:2015/api/v1/version
            - USER_AGENT=
            - REDIS_HOST=redis
            - REDIS_DB=0
            - REDIS_CACHE_DB=1
            - DB_HOST=mariadb
            - DB_USERNAME=siwecos
            - DB_PASSWORD=siwecos
            - DB_DATABASE=coreApi
            - REDIS_CLIENT=phpredis
            - LOG_CHANNEL=stderr


    mariadb:
        image: mariadb:latest
        volumes:
            - db_production:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=siwecosRoot
            - MYSQL_USER=siwecos
            - MYSQL_PASSWORD=siwecos
            - MYSQL_DATABASE=coreApi

    redis:
        image: redis:latest

volumes:
    db_production:
    signatures_production:
